In [1]:
from pathlib import Path
import pandas as pd

CSV = Path("../data/PanTEon_Database_metadata_v1.6.1.csv")

df = pd.read_csv(CSV, dtype=str, keep_default_na=False)
print(df.shape)
print(list(df.columns))
df.head()

(2790, 13)
['Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Species', 'Library?', 'Source', 'Source 2', 'Notes', 'Selected', 'TE_count', 'MCH_Parameters']

,Kingdom,Phylum,Class,Order,Family,Species,Library?,Source,Source 2,Notes,Selected,TE_count,MCH_Parameters
0,Fungi,Basidiomycota,Agaricomycetes,Polyporales,Podoscyphaceae,Abortiporus biennis,Complete,RM2+MCH,,B-GUT,RM2+MCH,1,"x=0, e=500, c=1"
1,Fungi,Mucoromycota,Mucoromycetes,Mucorales,Cunninghamellaceae,Absidia caerulea,Complete,RM2+MCH,,B-GUT,RM2+MCH,10,"x=0, e=500, c=1"
2,Fungi,Mucoromycota,Mucoromycetes,Mucorales,Cunninghamellaceae,Absidia glauca,Complete,RM2+MCH,,B-GUT,RM2+MCH,1,"x=0, e=500, c=1"
3,Fungi,Mucoromycota,Mucoromycetes,Mucorales,Cunninghamellaceae,Absidia repens,Complete,RM2+MCH,,B-GUT,RM2+MCH,6,"x=0, e=500, c=1"
4,Animalia,Echinodermata,Asteroidea,Valvatida,Acanthasteridae,Acanthaster planci,complete,RM2+MCH,,"ENSEMBL ""2023""",RM2+MCH,71,"x=10, e=500, c=1"

In [2]:
COLS = ["Kingdom", "Phylum", "Class", "Order", "Family",
        "Species", "Source", "Source 2", "Notes"]
print("No encontradas:", [c for c in COLS if c not in df.columns])
sub = df[COLS].copy()

No encontradas: []

In [3]:
print((sub.apply(lambda s: s.str.strip() == "")).sum())
print("Species con espacios en los extremos:",
      (sub["Species"] != sub["Species"].str.strip()).sum())

Kingdom        0
Phylum         3
Class         49
Order         29
Family        76
Species        0
Source         0
Source 2    2740
Notes          6
dtype: int64
Species con espacios en los extremos: 0

In [4]:
print("Filas:", len(sub), "| Especies únicas:", sub["Species"].nunique())
sub[sub["Species"].duplicated(keep=False)].sort_values("Species")

Filas: 2790 | Especies únicas: 2790

Empty DataFrame
Columns: [Kingdom, Phylum, Class, Order, Family, Species, Source, Source 2, Notes]
Index: []

In [5]:
print(sub["Source"].value_counts())
print(sub["Source 2"].value_counts())

Source
RM2+MCH    2404
Dfam        386
Name: count, dtype: int64
Source 2
                             2740
Repbase                        45
Genero coincidente              2
Genero y familia repetido       1
Obtained by Johan P.            1
Dfam                            1
Name: count, dtype: int64

In [6]:
sp = sub["Species"]
raros = ~sp.str.fullmatch(r"[A-Za-z .\-']+")
print("Con doble espacio:", sp.str.contains("  ").sum())
print("Con caracteres no esperados:", raros.sum())
sp[raros].head(10)

Con doble espacio: 0
Con caracteres no esperados: 11

250                  Ascobolus immersus rn42
471     Basidiobolus meristosporus cbs 93173
1136                    Exophiala sp hkrs030
1208                 Gaeumannomyces sp js464
1325                      Helotiales sp f229
1488         Leptodontidium sp mpisdfrat0119
1688                    Morchella sp 2018w30
1786                          Nectria sp b13
2493                       Sycophila sp sp 5
2524          Terfezia boudieri atcc mya4762
Name: Species, dtype: str

In [7]:
print(sp[raros].str.findall(r"[^A-Za-z .\-']").explode().unique())
sp[raros]

<StringArray>
['4', '2', '9', '3', '1', '7', '0', '6', '8', '5']
Length: 10, dtype: str

250                  Ascobolus immersus rn42
471     Basidiobolus meristosporus cbs 93173
1136                    Exophiala sp hkrs030
1208                 Gaeumannomyces sp js464
1325                      Helotiales sp f229
1488         Leptodontidium sp mpisdfrat0119
1688                    Morchella sp 2018w30
1786                          Nectria sp b13
2493                       Sycophila sp sp 5
2524          Terfezia boudieri atcc mya4762
2778             Zopfia rhizophila cbs 20726
Name: Species, dtype: str

In [19]:
from pathlib import Path
import pandas as pd

CSV = Path("../data/PanTEon_Database_metadata_v1.6.1.csv")

COLS = ["Kingdom", "Phylum", "Class", "Order", "Family",
        "Species", "Source", "Source 2", "Notes"]

# Leer todo como texto y sin convertir vacíos a NaN
crudo = pd.read_csv(CSV, dtype=str, keep_default_na=False)

# Comprobar que no falta ninguna columna
faltan = [c for c in COLS if c not in crudo.columns]
assert not faltan, f"Columnas no encontradas: {faltan}"

# Quedarse solo con las 9 columnas, en el orden del enunciado
datos = crudo[COLS].copy()

print(datos.shape)
print(list(datos.columns) == COLS)
datos.head()

(2790, 9)
True

,Kingdom,Phylum,Class,Order,Family,Species,Source,Source 2,Notes
0,Fungi,Basidiomycota,Agaricomycetes,Polyporales,Podoscyphaceae,Abortiporus biennis,RM2+MCH,,B-GUT
1,Fungi,Mucoromycota,Mucoromycetes,Mucorales,Cunninghamellaceae,Absidia caerulea,RM2+MCH,,B-GUT
2,Fungi,Mucoromycota,Mucoromycetes,Mucorales,Cunninghamellaceae,Absidia glauca,RM2+MCH,,B-GUT
3,Fungi,Mucoromycota,Mucoromycetes,Mucorales,Cunninghamellaceae,Absidia repens,RM2+MCH,,B-GUT
4,Animalia,Echinodermata,Asteroidea,Valvatida,Acanthasteridae,Acanthaster planci,RM2+MCH,,"ENSEMBL ""2023"""

In [20]:


# quitar espacios en las 9 columnas
tras_strip = datos.apply(lambda col: col.str.strip())


cambios_strip = (datos != tras_strip).sum()
print("Valores modificados por strip:")
print(cambios_strip[cambios_strip > 0] if cambios_strip.sum() else "ninguno")

# vacio a nulo, y forzar None real (no NaN) para que MongoDB guarde null
datos = tras_strip.replace("", None)
datos = datos.astype(object).where(datos.notna(), None)

# Comprobaciones
print("\nNulos por columna:")
print(datos.isna().sum())
print("\nCadenas vacías restantes:", (datos == "").sum().sum())

vacio = datos.loc[datos["Phylum"].isna(), "Phylum"].iloc[0]
print("Tipo de un vacío:", type(vacio).__name__)

Valores modificados por strip:
Phylum    1
Class     1
Order     9
Family    2
dtype: int64

Nulos por columna:
Kingdom        0
Phylum         3
Class         49
Order         29
Family        76
Species        0
Source         0
Source 2    2740
Notes          6
dtype: int64

Cadenas vacías restantes: 0
Tipo de un vacío: NoneType

In [25]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path("..").resolve()))

%load_ext autoreload
%autoreload 2

from pipeline.limpiar import limpiar_csv, clave


limpio = limpiar_csv(CSV)

print(limpio.shape)                               # (2790, 10)
print(limpio["species_key"].nunique())            # 2790
print(limpio["Species"].tolist() == crudo["Species"].tolist())

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
(2790, 10)
2790
True

In [ ]:
import io
import pandas as pd

# as filas tienen comillas
mask = limpio["Notes"].str.contains('"', na=False)
print("Filas con comillas:", mask.sum())
print(limpio.loc[mask, "Notes"].value_counts())

print("\nValores únicos de Notes:")
print(limpio["Notes"].value_counts(dropna=False))


buf = io.StringIO()
limpio.to_csv(buf, index=False)
buf.seek(0)
releido = pd.read_csv(buf, dtype=str, keep_default_na=False)

print("\nNotes idéntico tras exportar y releer:",
      limpio["Notes"].fillna("").tolist() == releido["Notes"].tolist())

Filas con comillas: 748
Notes
ENSEMBL "2023"    375
ENSEMBL "2025"    373
Name: count, dtype: int64

Valores únicos de Notes:
Notes
B-GUT                 1479
ENSEMBL "2023"         375
ENSEMBL "2025"         373
Curated Dfam           293
Uncurated Dfam         165
Release 1.2             43
Dfam no especie         34
APTEdb                  12
No especie Repbase      10
None                     6
Name: count, dtype: int64

Notes idéntico tras exportar y releer: True

In [26]:
limpio = limpiar_csv(CSV)
print(limpio.shape)                                  # (2790, 11)
print(limpio["source_2"].value_counts(dropna=False)) # Repbase 45, Dfam 1, None 2744
print(limpio["annotation"].value_counts(dropna=False)) # 4 valores, None 2786
print(limpio["source_2"].notna().sum() + limpio["annotation"].notna().sum())  # 50
print(limpio["Species"].tolist() == crudo["Species"].tolist())  # True

(2790, 11)
source_2
None       2744
Repbase      45
Dfam          1
Name: count, dtype: int64
annotation
None                         2786
Genero coincidente              2
Genero y familia repetido       1
Obtained by Johan P.            1
Name: count, dtype: int64
50
True

In [13]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path("..").resolve()))

import pandas as pd
from pipeline.limpiar import TAXONOMIA, MARCADOR_FALTANTE

crudo = pd.read_csv("../data/PanTEon_Database_metadata_v1.6.1.csv", dtype=str, keep_default_na=False)
for c in TAXONOMIA:
    print(c, crudo[c][crudo[c].str.strip().str.match(MARCADOR_FALTANTE)].value_counts().to_dict())

Kingdom {}
Phylum {}
Class {}
Order {'No trobat': 7, 'No order': 5, 'No ordre NCBI': 2, 'No Orden No trobat': 2, 'No ordre NCBI Caenogastropoda incertae sedis': 1, 'No order (eupecaria incertae sedis)': 1, 'No order Dothideomycetes incertae sedis': 1}
Family {}